nodeLinker: hoisted
allowBuilds:
  electron-winstaller: true
  fs-xattr: true
  macos-alias: true
minimumReleaseAgeExclude:
  - '@electron-forge/cli@8.0.1'
  - '@electron-forge/core-utils@8.0.1'
  - '@electron-forge/core@8.0.1'
  - '@electron-forge/maker-base@8.0.1'
  - '@electron-forge/maker-deb@8.0.1'
  - '@electron-forge/maker-dmg@8.0.1'
  - '@electron-forge/maker-rpm@8.0.1'
  - '@electron-forge/maker-squirrel@8.0.1'
  - '@electron-forge/maker-zip@8.0.1'
  - '@electron-forge/multi-logger@8.0.1'
  - '@electron-forge/plugin-base@8.0.1'
  - '@electron-forge/publisher-base@8.0.1'
  - '@electron-forge/shared-types@8.0.1'
  - '@electron-forge/tracer@8.0.1'
  - electron@44.5.1
